<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8' />
	<title>Teamskeets :: Noobies</title>
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_INDEX; ?>/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_INDEX; ?>/css/main.css">
	<script type='text/javascript' src='<?php echo BASE_INDEX; ?>/js/jquery-1.10.2.min.js'></script>
	<script type='text/javascript' src='<?php echo BASE_INDEX; ?>/js/jquery-ui.min.js'></script>
	<script type='text/javascript' src='<?php echo BASE_INDEX; ?>/js/bootstrap.min.js'></script>
	
</head>	
<body>
	<div id='bg'>
		<div class='navbar navbar-default navbar-fixed-top'>
			<div class='container'>
				<div class='navbar-header'>
					<a class='navbar-brand' href='<?php echo BASE_URL; ?><?php echo BASE_VERSION; ?>'>Search Model</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class='dropdown'>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">By Name <b class="caret"></b></a>
							<ul class='dropdown-menu'>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls">Random Models</a></li>
								<li class="divider"></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/a-b-c-d">A-B-C-D</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/e-f-g-h">E-F-G-H</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/i-j-k-l">I-J-K-L</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/m-n-o-p">M-N-O-P</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/q-r-s-t">Q-R-S-T</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/u-v-w-x">U-V-W-X</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/alpha/y-z">Y-Z</a></li>
							</ul>							
						</li>	
						<li class='dropdown'>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">By Tags <b class="caret"></b></a>
							<ul class='dropdown-menu'>								
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/18">18</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/Teen">Teen</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/Amateur">Amateur</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/Blonde">Blonde</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/Butt">Butt</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/Black">Black</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/tags/Asian">Asian</a></li>
							</ul>
						</li>
												
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">By Sites <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls">Teamskeet</a></li>
								<li class="divider"></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/ih">Innocent High</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/si">Solo Interview</a></li>							
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/oye">Oyeloca</a></li>							
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/trw">The Real Workout</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/hfy">Her Fresh Man Year</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/tgs">This Girl Sucks</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/ta">Titty Attack</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/pl">POV Love</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/sd">Self Desire</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/sn">Shes New</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/tb">Teeny Black</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/es">Exxxtra Small</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/rt">Ruba Teen</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/tp">Teens Do Porn</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/ss">Step Siblings</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/tc">Teens Curve</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/lh">Lush HD</a></li>
								<li><a href="<?php echo BASE_VERSION; ?>/noobies/girls/sites/bff">BFF's</a></li>
							</ul>
						</li>
					</ul>
					<form method='GET' action="<?php echo BASE_VERSION; ?>/noobies/girls/search/">
					<div class='nav navbar-nav navbar-right col-lg-3'>
						
						<div class="col-sm-12 pull-right" style='line-height:45px;'>
							<div class="input-group-sm input-group">
								
									<input name='gname' type="text" class="form-control" placeholder='Search' style='border:1px solid #000;'>
									<span class="input-group-btn">
										<button style='top:0px; width:30px !important;' class="btn btn-default glyphicon glyphicon-search" type="button"></button>
									</span>
								
							</div>
						</div>					
						
					</div>
					</form>
				</div>
				
			</div>
		</div>
		<div class='spacetop' style='height:60px;width:1px;'></div>
		
		<?php echo $content; ?>
		
		<div class='container'>		
			<footer>All Rights Reserved</footer>		
		</div>
	</div>		
	
</body>
</html>