<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8' />
	<title>Paperskeets :: Noobies</title>
	<link rel="stylesheet" type="text/css" href="/programmer122013/paulon/public/css/bootstrap.min.css">
</head>	
<body>
	
	<div class='container'>
	<header>Paperskeets Noobies</header>	
		<div class='row'>
			<div class='col-sm-12'>
			<?php echo $content; ?>
			</div>
		</div>
	<footer>All Rights Reserved</footer>		
	</div>
	
</body>
</html>